spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: liu123456

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


logging:
  level:
    root: warn
    com.liu.blog: info
  file:
    name: log/blog-pro.log
server:
  port: 8081
